### ISSUE TITLE
pagination issue

### ISSUE THREAD

**Issue by sasikanth513** [aslagle/reactive-table#139]
For one my columns I'm using checkbox like below

```
return new Spacebars.SafeString('<input class="checkbox regCheckbox" type="checkbox" id="'+value+'" >'+getName(object.email));
```

and no of rows per page is `10`

when I select all checkboxes and goto another checkbox and comeback to this page all the checkboxes are deselected.

and also I've 200-300 records and every page has 10 records, when I click on selectAll button I want all the checkboxes(200) to be selected.

I'm doing this way, checking for the checkbox and selecting the checkbox

`$(".regCheckbox").prop('checked', true);`

Is there any better ways of doing these?

**Comment by tarzak** [comment]
Hello :).
I have got probably similar problem. I'm trying to make something kind of Gmail's check all letters functionality.
I'm push()'ing all the selected rows' data to array inside of ReactiveVar() of my `reactive table`. So I can track if row is checked by comparing its data context with `reactive table`'s Reactive Array. But I can't properly check if all rows are checked on the other page. So checkbox in the header of the `reactive table` does not work properly. Mb someone knows how it can be possible.... For example, how to access to data context of all rows that should be rendered on specific page?

When I want to add all rows presented on the current page of `reactive table`, I'm using `template.$('.checkbox')`, then with Blaze.getData() making array of data of these rows and pushing it to ReactiveVar in reactive table. But when i switching page and trying to find out if next page's rows are added, this way does not work properly, because (I guess) there is very little moment of the time, when old rows have not destroyed yet and new ones have not rendered yet and I'm getting the same result with `template.$('.checkbox')`, like was on previous page.

**Comment by tarzak** [comment]
Hey how about, to store data context of rows which are present on current page in ReactiveVar in `reactive table`'s template.context? And modify it from helper `sortedRows`?

**Comment by aslagle** [comment]
I'm not sure I understand exactly what you're trying to do, but I would suggest putting the checkbox states in a ReactiveDict that maps the row's ids to true or false. It should contain all the rows, not the ones on the current page. When a box is checked, update the value for that row's id in the dict, and when rendering the cell with the checkbox, look up the value for that row's id. For the checkbox in the header, you could look at all the values.
