### ISSUE TITLE
Feature Request: Allow template for no data/loading

### ISSUE THREAD

**Issue by peterchoo** [aslagle/reactive-table#200]
I have a table that changes it's data based on the context provided.  Sometimes there is no data for a particular context.

Could we have the option to pass a "no-data" template?

Additionally, in my application I have a reactive table driven by a client side collection, with data fetched from a REST API and as three is no bulk insert/upsert command available, the data has to be looped over and upserted individually.  This causes a lot of  re-draws of the reactive-table.  It would be useful to have a "loading" template and to be able to set reactive-table into a "loading" state so it displays this template and doesn't redraw until it is no longer in the loading state.

Your thoughts?

Thanks for taking the time to read this.

**Comment by aslagle** [comment]
I've been using if/else in templates in my applications to render reactiveTable or a no-data template if it's empty, but I think passing in a no-data template sounds better. Especially for a server-side collection, since the application needs an additional pub/sub or call to determine if the collection's empty when the table already has that info.

For the loading template though, I'd rather keep it outside the package since it's the application that can determine the loading state.

**Comment by peterchoo** [comment]
:+1: for the no data template, that will be really useful.

For the loading state stuff, is there a way of "pausing the reactivity" of the table? by this I mean prevent any re-draws from triggering?  The work around I'm using right now is if/else templates in my application controlled by a reactive var while I'm loading the data :D

**Comment by aslagle** [comment]
No, sorry. I think it would be difficult, and the pagination and sorting controls are also using reactive variables. If you can set some sort of flag or creation date in your data, you could try filtering the table to leave out the new items until they're ready.

**Comment by aslagle** [comment]
In the latest version I added a noDataTmpl option.

**Comment by peterchoo** [comment]
Thanks!
