### ISSUE TITLE
Is there a key about: Nested key ? and more....

### ISSUE THREAD

**Issue by carrot93** [aslagle/reactive-table#227]
fields:[{key:"user.$.address"... not support? just fit user.0.address for 1 item?

And in the example of readme.md(custom filter), can't execute 'template.filter.set' ( error: template is not defined) ,only 'filter.set' passed.

**Comment by aslagle** [comment]
The key option only supports one item per cell, but you could write a custom function to combine an array into one item.
```
fields: [{key: 'users', label: 'Addresses', fn: function (users) { return _.pluck(users, 'address').join(", "); }]
```

If template is not defined, maybe you're missing the template argument to the event handler function you're calling it from?

**Comment by carrot93** [comment]
Yep. just like the schema:
```
   users:type [String]
   'users.address':type String
   'users.phone':type String
   ....
```
And I wanna that
```
table:
Address              |   Phone
users.0.address  |  users.0.phone
users.1.address  |  users.1.phone
````

follow your way I got :
Address            |   Phone 
address1,address2,...  |  phone1,phone2,phone3 

Any idea? 

For the custom filter, I try:
```
@filter= new ReactiveTable.Filter 'newFilter',['_Id']
Template.test.created = () ->
   #this line is  no effect
   @filter = new ReactiveTable.Filter 'newFilter',['_id']

Template.test.events
  'click .button': ->
#    this line is no result
#      template.filter.set @_id
# this line is ok
      filter.set @_id

<template name="test">
{{>reactiveTableFilter id="newFilter" label="test"}}
{{>reactiveTable collection=Test settings=settings}}

Template.test.helpers
  setttings: ->
  {
      collections: Test
      fields: [
           {
               key: "users"
               label: "user's Address"
               fn:(users) ->
                     return _.pluck(users,'address').join(",")
            },
            ...
         ]
   }

```

**Comment by aslagle** [comment]
Ah I see. Having multiple rows for the same item in the collection isn't supported. If it's a small collection, you could transform it yourself and use an array of users as the collection for reactiveTable.

```
collection: _.chain(Test).pluck('users').flatten().value()
fields:  [{ key: 'address', label: 'User's Address'}]
```

For the custom filter, you have a global variable named 'filter' at the top. You can use that instead of creating one in Template.created and use filter.set in the event handler, but that one filter will be shared for all instances of your template.
 
My example in the README doesn't use global variables, it creates a filter inside the template instance. The reason template.filter.set didn't work is that you're missing the arguments to the event handler: 
```
'click .button': (event, template) ->
```

**Comment by carrot93** [comment]
Thx. you inspired me. I adjust my datastructure to fit the feature of reactive-table.

And more, collection: _.chain ... has servial problem for null data. It causes the: typeError, reactiveTable arguments must be collection ....

For custom filter, u r right. I fixed my fault.
