### ISSUE TITLE
Filter not firing when new data is added

### ISSUE THREAD

**Issue by kluch** [aslagle/reactive-table#289]
Hi,

I have a page with a table. The page is subbed to a collection. The table gets its data from
Html:
`{{> reactiveTable collection=getDataHelper settings=settings }}`

getDataHelper contents:
`return Collection.find({search params}).fetch();`

Settings just returns the fields that should be dispplayed.

The filter works fine normally but when I add a new item to it on another page and navigate back the filter does not fire. I put in a breakpoint on the "getRowCount" helper in reactive_table.js and it does not hit it at all. If I click on a header to sort the data though then the filter works again and starts hitting the breakpoint etc.

Any help/advice would be appreciated.

**Comment by aslagle** [comment]
I'm not sure what the problem is, but you could try setting the id option - if you don't set an id it will generate a unique one and it will change when you leave the page and come back, which could cause issues with the filter.

You also don't need fetch in getDataHelper - if you use a cursor instead of an array as the collection it will probably be faster. But I don't think that would affect the filter at all.

**Comment by kluch** [comment]
Hi,

Awesome thanls, adding a ID to `{{> reactiveTable collection=getDataHelper settings=settings }}` fixed this issue. 

Also thanks for the .fetch tip.
