### ISSUE TITLE
Server side filtering not working in v0.8.30

### ISSUE THREAD

**Issue by s7dhansh** [aslagle/reactive-table#384]
It was working till 0.8.21 for sure. After that I updated to 0.8.30 directly (after disablePageReactivity). The filters are not working now.
Any ideas why?

I will try and report the exact version from which they start failing.

**Comment by s7dhansh** [comment]
It's not working since 0.8.29

**Comment by s7dhansh** [comment]
The problem is line 182 in https://github.com/aslagle/reactive-table/compare/v0.8.28...v0.8.29. I created some reactive filters in my template, and instead of them being used, new filters are created through this line I suppose.

**Comment by aslagle** [comment]
If you create the filters again it shouldn't matter, except I noticed it doesn't update the fields if they're not set the first time.

Try adding `reactiveTableFilters[id].fields = fields;` above this line: https://github.com/aslagle/reactive-table/blob/master/lib/filter.js#L141 and see if that helps.

Otherwise I don't know what the problem is.

**Comment by s7dhansh** [comment]
https://github.com/aslagle/reactive-table/pull/385
