### ISSUE TITLE
Problem with server?

### ISSUE THREAD

**Issue by thearabbit** [aslagle/reactive-table#390]
I don't understand about server publish `name vs collection`
```js
name: The name of the publication
collection: A function that returns the collection to publish (or just a collection, if it's insecure).
```
Ex:
```js
// Client
let setting = {
                name:'pubPost',
                collection: Post,
............

// Both
Post = new Mongo.Collection('post');

// Server
ReactiveTable.publish("pubPost", Post);
```
What difference `name vs collection`?

**Comment by aslagle** [comment]
I guess it is confusing since the server- and client-side settings are named differently.

On the server, `name` is a string you choose to refer to the ReactiveTable publication, and `collection` is the Meteor Collection you want to publish.

On the client side, the `collection` is the string you used as the `name` for the publication on the server. If you aren't using the server-side publish, `collection` can also be a Meteor Collection.

So in the example you have, the server part is correct, but the client part should be:
```
let setting = { collection: 'pubPost' }
```

**Comment by thearabbit** [comment]
Thanks for your explain.
