### ISSUE TITLE
Condition with selector

### ISSUE THREAD

**Issue by rmuratov** [aslagle/reactive-table#391]
Hello.

I use [alanning:roles](https://atmospherejs.com/alanning/roles) to manage permissions and want to implement publication which publishes set of data depending on the role - one set to one role, another to another and nothing to anybody else. And I am in little trouble.

First implementation:

~~~coffee
ReactiveTable.publish 'secretData', SecretData, ->
  if Roles.userIsInRole @userId, ['god']
    {}
  else if Roles.userIsInRole @userId, ['semigod']
    {allowedToSemigod: @userId}
~~~

Surprisingly, if the current user is not a `god` or `semigod` they gets full `SecretData` collection.

I ended with solutionion where there is final `else`, which guaranteed returns nothing:

~~~coffee
else
  {_id: {$exists: false}}
~~~

Is there any better solution? If not, I think described behavior should be documented.

**Comment by aslagle** [comment]
I probably would have done this by using a function for the collection as well, so that users that aren't in one of the roles won't have any collection published at all.

But I think you're right that the behavior when the selector function returns undefined is surprising. Probably it should abort and not publish anything in that case as well. Unfortunately changing this wouldn't be backwards-compatible.
