### ISSUE TITLE
Adding a tooltip in column header stops working when sorting that column

### ISSUE THREAD

**Issue by U54** [aslagle/reactive-table#394]
I am trying to have a [tooltip](http://getbootstrap.com/javascript/#tooltips) in my column title that way when a user puts their cursor over it a little bit of information about the column will popup. Here is what I have to make this work:

```
{ key: 'example',
  label: function () { 
    return new Spacebars.SafeString('<span data-toggle="tooltip" title="This is some example text for the tooltip!">Example Title </span>'); 
  }
},
```

```
Template.myTemplate.onRendered(function() {
    // Tooltip
    $("[data-toggle=tooltip]").tooltip();
});
```

When I first refresh the page it works exactly as it should and when I put my cursor over the title the tooltip appears. The issue I am having is when I click on that title to sort the table based on that column, when I do this the tooltip stops working. I can click on any of the other column titles and sort the table based on those and it will still work, but when I click this one with the tooltip it causes the tooltip to not work anymore unless I refresh the page. 

Any ideas on why this would be happening or how I could fix it?

**Comment by aslagle** [comment]
I think I know why it's happening - the tooltip() call in onRendered only affects the elements currently rendered, and when the sort changes the table header is rendered again, removing the old element and creating a new one. 

I would recommend creating a template to use as your label instead of the function - then you can use its onRendered and it will get called every time the label is rendered within the overall template.

**Comment by U54** [comment]
@aslagle Thank you for the reply and info! Your suggestion worked, I used a template for the label instead of the function and that solved the issue. Thanks!
